language: bash
services: docker

env:
  - VERSION=bionic
  - VERSION=buster
  - VERSION=cosmic
  - VERSION=disco
  - VERSION=jessie
  - VERSION=sid
  - VERSION=stretch
  - VERSION=trusty
  - VERSION=xenial

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - export image="buildpack-deps:$VERSION"

script:
  - test "$(head -n1 Dockerfile)" = "FROM $image-scm"
    && test "$(head -n1 scm/Dockerfile)" = "FROM $image-curl"
    && [[ "$(head -n1 curl/Dockerfile)" == 'FROM debian:'*
       || "$(head -n1 curl/Dockerfile)" == 'FROM ubuntu'*':'* ]]
  - travis_retry docker build -t "$image-curl" curl
  - travis_retry docker build -t "$image-scm" scm
  - travis_retry docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
